name: my first action
on: [push]
jobs:
  run-some-scripts:
    runs-on: windows-latest
    steps:
      - name: find path
        run: cd C:\Users\DHI-LAP\IdeaProjects\YAMLTEST\src\main\java\com\example\yamltest
      - name: compile java
        run: javac Main.java
      - name: run script
        run: java Main