name: my first action
on: [push]
jobs:
  run-some-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: find path
        run: cd ~/IdeaProjects/YAMLTEST/src/main/java/com/example/yamltest
      - name: compile java
        run: javac Main.java
      - name: run script
        run: java Main
