name: my first action

on: [push]

jobs:
  run-some-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: compile java
        run: javac Main.java
      - name: run scipt
        run: |
            java Main
